[FEAT] 메인 화면 api
HapdongSeminarApp4/Korail-Server pull request #2
Opened 2022-11-21 13:57 UTC by biiit4894

메인 화면 api를 1차적으로 만들어 보았읍니다!

### 궁금한 점
1. ERD 상으로는 ticket 테이블에 **`seat_num`, `trail`** 필드도 존재해서 그 둘도 `/ticket` 상에 리스폰스 되도록 했는데.. 메인 화면 상에서 사실 쓸 일이 없을 것 같아서.. 
    - **클라 분들이 편하시게 그 둘을 빼서 리턴하게 해야할까요**...?!

3. 메인 화면상에 보이는 티켓 데이터도 결국 어떤 유저의 데이터이니,, 이걸 특정 유저 티켓 조회로 짜줘야 하나 그냥 전체 티켓 조회로 짜야 하나 고민하다 `전체 티켓 조회`에 해당하는 `getAllTicket`이 나왔네요..
    - 특정 유저 티켓 조회는 `/ticket/:userId/:ticketId` 로 라우팅되어있고, `getTicketById`인데 삭제하는 것이 맞다면 알려주세요!😎
    <img src="https://user-images.githubusercontent.com/82032418/203072677-36b6e375-15dd-415c-8a21-6de17bee1536.JPG">

2022-11-22 15:36 UTC, thguss commented
1. 클라 쪽에서 필요없는 데이터라면 보내주지 않는 것이 원칙적으로 좋아요. 하지만 문제 발생 여부는 없습니다! 편하신대로 해도 됩니당~!
2. 메인 화면 상에 보이는 티켓은 어떤 유저도 예매하지 않은 "그냥 티켓"이기 때문에 유저 정보 없이 전체적으로 그냥 보여주는 것이 맞는 것 같습니다! 유저 정보와 관련해서 조회하는 api는 제가 담당한 쪽에 해당해요~~ 지워주시면 될 것 같습니다! 잘 고르셨네요 ㅎㅎ

2022-11-22 15:44 UTC, thguss requested changes
수고하셨습니다~~ 비즈니스 로직 잘 짜셨네요 ㅎㅎ 언급드린 몇 부분은 함께 얘기 나눠봐요!

1. url에 api 포함 여부
2. 승차권 반환 타입 의논 (이 부분은 한빛님 의견을 전적으로 따를게요! 원하신 플로우로 해주세요~)

2022-11-22 15:44 UTC, thguss commented on prisma/schema.prisma
>  }
prisma 관련해서 저희가 korail이라는 스키마를 따로 만들어서 뺐던 것 같은데 public으로 url이 설정되어 있어서 db가 좀 꼬였더라구요 ㅠㅠ 그래서 제가 다시 korail로 빼서 고쳐놨으니 korail 스키마로 쓰시면 될 것 같습니다..!! url은 제가 카톡으로 보내드릴게요 :)

2022-11-22 15:44 UTC, thguss commented on src/controller/ticketController.ts
> +const getTicketById = async (req: Request, res: Response) => {
삭제해주시면 될 것 같아요!

2022-11-22 15:44 UTC, thguss commented on src/controller/ticketController.ts
> +  const data = await ticketService.getAllTicket();
"티켓들"을 조회하는 것이 아닌 한 티켓을 조회하는 것으로 알고 있어서..!! 함수명을 `getAllTicket` 보다는 `getTicket` 으로 고치는 것이 좀 더 의미상 가까울 것 같아요!

2022-11-22 15:44 UTC, thguss commented on src/controller/ticketController.ts
> +const getAllTicket = async (req: Request, res: Response) => {
이 함수명 역시 `getTicket` 이 의미적으로 좀 더 직관적일 것 같아요!

2022-11-22 15:44 UTC, thguss commented on src/index.ts
> -app.get("/", (req: Request, res: Response, next: NextFunction) => {
삭제한 이유를 알 수 있을까요?~?

2022-11-22 15:44 UTC, thguss commented on src/index.ts
> -app.use("/api", router); // use -> 모든 요청
저는 api를 추가한 경우로 생각하고 명세서를 다시 써놔서..!! 이 부분은 다시 의논해보는 것이 좋을 것 같아요~

2022-11-22 15:44 UTC, thguss commented on src/router/ticketRouter.ts
> +router.get("/:userId/:ticketId", ticketController.getTicketById);
지워주세용~

2022-11-22 15:44 UTC, thguss commented on src/service/ticketService.ts
> +const getAllTicket = async () => {
앞에서 언급했듯이, `getTicket` 이라는 함수명이 의미적으로 좀 더 가까울 것 같아요!

2022-11-22 15:44 UTC, thguss commented on src/service/ticketService.ts
> +  const data = await prisma.ticket.findMany();
제가 알기로는 메인 화면에는 티켓 "하나"만 조회되는 것으로 알고 있어요! 그래서 
1. `data[0]`으로 리턴을 하는 경우
2. 날짜를 입력값으로 받아서 조회하는 경우

둘 중 하나로 고치면 좋을 것 같아요~

2022-11-22 15:44 UTC, thguss commented on src/service/ticketService.ts
> +const getTicketById = async (userId: number, ticketId: number) => {
지워주세용!~!

2022-11-23 03:39 UTC, biiit4894 commented on src/controller/ticketController.ts
> +  const data = await ticketService.getAllTicket();
그쵸그쵸 감사합니다!!

2022-11-23 03:44 UTC, biiit4894 commented on prisma/schema.prisma
>  }
넵 env 수정과 db pull&generate 완료했습니다!

2022-11-24 06:00 UTC, biiit4894 commented on src/index.ts
> -app.use("/api", router); // use -> 모든 요청
아 명세서에 /ticket으로 되어있어서 지웠는데 그러면 /api에서 시작하는걸로 할게요!!

2022-11-24 06:02 UTC, biiit4894 commented on src/index.ts
> -app.get("/", (req: Request, res: Response, next: NextFunction) => {
아아 무조건 /ticket을 입력했을 경우만 생각하고 url로 아무것도 입력되지 않았을때를 생략해버렸는데
생각해보니 그냥 접속했을때도 접속에 성공했다고 안내문구를 적어두는게 덜 당황스럽고 맞을 것 같네요..!
고쳐둘게요~!!

2022-11-24 06:21 UTC, biiit4894 commented on src/service/ticketService.ts
> +  const data = await prisma.ticket.findMany();
앗 넵!! 일단 data[0]으로 리턴되게 해두었어요!

2022-11-24 08:58 UTC, biiit4894 commented
> 1. 클라 쪽에서 필요없는 데이터라면 보내주지 않는 것이 원칙적으로 좋아요. 하지만 문제 발생 여부는 없습니다! 편하신대로 해도 됩니당~!
> 2. 메인 화면 상에 보이는 티켓은 어떤 유저도 예매하지 않은 "그냥 티켓"이기 때문에 유저 정보 없이 전체적으로 그냥 보여주는 것이 맞는 것 같습니다! 유저 정보와 관련해서 조회하는 api는 제가 담당한 쪽에 해당해요~~ 지워주시면 될 것 같습니다! 잘 고르셨네요 ㅎㅎ

1. 친절한 답변 넘나 감사합니다.. 1번은 호옥시 몰라서 바꾸지 않고 그대로 두었어요!
2. 넵 불필요한 함수 지우고 getTicket으로 바꾸어뒀습니다!

2022-11-24 09:00 UTC, biiit4894 commented
> 수고하셨습니다~~ 비즈니스 로직 잘 짜셨네요 ㅎㅎ 언급드린 몇 부분은 함께 얘기 나눠봐요!
> 
> 1. url에 api 포함 여부
> 2. 승차권 반환 타입 의논 (이 부분은 한빛님 의견을 전적으로 따를게요! 원하신 플로우로 해주세요~)

논의점 정리 정말 감사해요..!
1. /ticket에서 시작하는걸로 생각해버렸는데  url에 api 포함되도록 수정했습니다!! 
2. data[0]으로 리턴되게 했습니다!!

2022-11-24 09:37 UTC, merged